baseURL: "https://pranavponni.github.io/" 
title: Pranav Ponnivalavan's Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Pranav Ponnivalavan's research, CV, work experience, projects, and contact information."
    author: Pranav Ponnivalavan
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pranav Ponnivalavan
          subtitle: "Undergraduate Student at Waseda University, Tokyo, Japan"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Work
              url: work/
            - name: CV
              url: cv/
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:pranavponnivalavan@waseda.jp
        - name: GitHub
          url: https://github.com/PranavPonni
        - name: YouTube
          url: https://www.youtube.com/@pranavponnivalavan4804
        - name: Twitter
          url: https://x.com/PranavPonni
        - name: LinkedIn
          url: https://www.linkedin.com/in/pranav-ponnivalavan-619733186

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2