baseURL: "https://pranavponni.github.io/" 
title: Pranav Ponnivalavan
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5
        - name: Work
          url: work/
          weight: 2
        - name: CV
          url: cv/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4

params:
    description: "This website hosts Pranav Ponnivalavan's research, CV, work experience, projects, and contact information."
    author: Pranav Ponnivalavan
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","work","cv","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pranav Ponnivalavan
          subtitle: "Hello, I’m Pranav — a 4th-year Mechanical Engineering student at Waseda University researching in-hand dexterous manipulation through body schema and cognitive touch in Shigeki Sugano and Tetsuya Ogata Labs."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Work
              url: work/
            - name: CV
              url: cv/
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:pranavponnivalavan@waseda.jp
        - name: GitHub
          url: https://github.com/PranavPonni
        - name: YouTube
          url: https://www.youtube.com/@pranavponnivalavan4804
        - name: Twitter
          url: https://x.com/PranavPonni
        - name: LinkedIn
          url: https://www.linkedin.com/in/pranav-ponnivalavan-619733186

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "pranavponnivalavan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2