baseURL: "https://pranavponni.github.io/" 
title: Pranav Ponnivalavan
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: CV
          url: cv/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4



params:
    description: "This website hosts Pranav Ponnivalavan's research, CV, work experience, projects, and contact information."
    author: Pranav Ponnivalavan
    DateFormat: "June 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","cv","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pranav Ponnivalavan
          subtitle: 'Hello, I’m Pranav — a 4th-year Mechanical Engineering undergraduate student at Waseda University; part of the <a href="https://sites.google.com/site/bashifunabashi/" style="text-decoration: underline;">AI Robot Manipulation Lab., Funabashi Group of Sugano Lab</a> for researching in-hand dexterous manipulation through body schema and cognitive touch, co-advised by <a href="https://www.sugano.mech.waseda.ac.jp/project.html" style="text-decoration: underline;">Shigeki Sugano</a> and <a href="https://ogata-lab.jp/projects.html" style="text-decoration: underline;">Tetsuya Ogata</a>.'
          imageUrl: "picture.jpg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Research
              url: research/
            - name: CV
              url: cv/
            - name: Projects
              url: projects/


    socialIcons:
        - name: Email
          url: mailto:pranavponnivalavan@waseda.jp
        - name: GitHub
          url: https://github.com/PranavPonni
        - name: YouTube
          url: https://www.youtube.com/@pranavponnivalavan4804
        - name: Twitter
          url: https://x.com/PranavPonni
        - name: LinkedIn
          url: https://www.linkedin.com/in/pranav-ponnivalavan-619733186

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "pranavponnivalavan"
      icon: hand.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2