import React from "react";
import "../assets/styles/Research.scss";

type Link = { label: string; href: string };

const links: Link[] = [
  { label: "arXiv", href: "https://arxiv.org/abs/2602.05468" },
  { label: "PDF", href: "https://arxiv.org/pdf/2602.05468" },
  { label: "DOI", href: "https://doi.org/10.48550/arXiv.2602.05468" },
];

const tags = [
  "Robotics",
  "Tactile sensing",
  "In-hand / in-grasp manipulation",
  "Predictive learning",
  "Sensory attenuation",
];

const phases = [
  {
    title: "Phase 1 - Learn self-touch dynamics",
    description:
      "Train a model to predict tactile feedback that arises purely from the hand's own motion and finger-finger contacts. This establishes what tactile patterns are expected and therefore less informative for manipulation.",
  },
  {
    title: "Phase 2 - Attenuation-guided motion learning",
    description:
      "Use the Phase-1 predictor during policy learning to reduce predictable self-touch components, effectively amplifying object-contact evidence in tactile observations. This helps policies remain robust even when self-contact is unavoidable.",
  },
];

const experiments = [
  {
    title: "Pencil lead insertion",
    description: "Insert a pencil lead into a mechanical pencil.",
  },
  {
    title: "Coin slot insertion",
    description: "Insert coins into a slot with varied poses and sizes.",
  },
  {
    title: "Paper-clip fixation",
    description: "Fix a paper clip onto a sheet of paper under pose variation.",
  },
];

const contributions = [
  "Introduces a two-phased framework to explicitly model self-touch tactile dynamics and reuse it for manipulation.",
  "Applies sensory attenuation to down-weight predictable self-contact and highlight object-contact signals.",
  "Demonstrates improved performance on fine-discrimination insertion tasks where self-contact is common.",
];

const pipelineStages = [
  {
    label: "Stage 1",
    title: "Self-touch prediction",
    description:
      "A predictor is trained to model tactile signals generated by the robot's own motion and finger-finger contact.",
  },
  {
    label: "Stage 2",
    title: "Sensory attenuation",
    description:
      "Expected self-touch is attenuated so external object contact remains salient in the tactile observation stream.",
  },
  {
    label: "Stage 3",
    title: "Policy learning",
    description:
      "Manipulation policies train on the attenuated representation for more reliable in-grasp insertion behavior.",
  },
];

const results = [
  {
    task: "Paper clip fixing",
    baseline: 70,
    tasa: 95,
    delta: "+25 pts",
    detail: "42/60 to 57/60 trials",
  },
  {
    task: "Coin insertion",
    baseline: 68,
    tasa: 92,
    delta: "+24 pts",
    detail: "61/90 to 83/90 trials",
  },
  {
    task: "Pencil lead insertion",
    baseline: 26,
    tasa: 58,
    delta: "+32 pts",
    detail: "66/250 to 146/250 trials",
  },
];

const resultNotes = [
  "The self-touch predictor tracked tactile activity closely, with reported correlations around r = 0.96 for the thumb and r = 0.98 for the index finger.",
  "TaSA reached 100% success on the reported unseen middle-placement evaluations for both paper clips and all coin sizes.",
  "The largest absolute gain appeared on pencil lead insertion, the most precision-sensitive task in the reported benchmark.",
];

const mediaItems = [
  {
    title: "Paper abstract",
    description: "Primary paper entry on arXiv with metadata and citation details.",
    href: "https://arxiv.org/abs/2602.05468",
    label: "Open arXiv",
  },
  {
    title: "Full PDF",
    description: "Direct preprint PDF for the full method, experiments, and figures.",
    href: "https://arxiv.org/pdf/2602.05468",
    label: "Open PDF",
  },
  {
    title: "Project page",
    description: "Project page with additional context for the self-touch manipulation work.",
    href: "https://sites.google.com/site/bashifunabashi/mhand-project/self-touch?authuser=0",
    label: "Open page",
  },
];

const mediaVideoSrc = `${process.env.PUBLIC_URL}/tasa%20short.mov`;

const bibtex = `@misc{ponnivalavan2026tasa,
  title  = {TaSA: Two-Phased Deep Predictive Learning of Tactile Sensory Attenuation for Improving In-Grasp Manipulation},
  author = {Ponnivalavan, Pranav and Funabashi, Satoshi and Schmitz, Alexander and Ogata, Tetsuya and Sugano, Shigeki},
  year   = {2026},
  eprint = {2602.05468},
  archivePrefix = {arXiv},
  primaryClass  = {cs.RO},
  doi    = {10.48550/arXiv.2602.05468}
}`;

function ResearchCard({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <section className="research-card">
      <div className="research-card-header">
        <h2>{title}</h2>
        {subtitle ? <p>{subtitle}</p> : null}
      </div>
      {children}
    </section>
  );
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = React.useState(false);

  return (
    <button
      type="button"
      className="research-copy-button"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1200);
        } catch {
          // noop
        }
      }}
    >
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function Research() {
  return (
    <div className="container" id="research">
      <section className="research-container">
        <header className="research-hero">
          <div className="research-tag-row">
            {tags.map((tag) => (
              <span key={tag} className="research-tag">
                {tag}
              </span>
            ))}
          </div>

          <h1>Research</h1>
          <h2 className="research-title">
            TaSA: Two-Phased Deep Predictive Learning of Tactile Sensory Attenuation for
            Improving In-Grasp Manipulation
          </h2>

          <p className="research-summary">
            TaSA tackles a practical bottleneck in dexterous robotic hands: during manipulation,
            robots must distinguish tactile signals caused by self-contact from those caused by
            external object contact. Inspired by human sensory attenuation, TaSA learns a
            self-touch prediction model first, then uses it to emphasize object-contact signals
            during policy learning.
          </p>

          <div className="research-links">
            {links.map((link) => (
              <a key={link.href} href={link.href} target="_blank" rel="noreferrer">
                {link.label}
              </a>
            ))}
          </div>

          <p className="research-meta">
            arXiv:2602.05468 · Submitted Feb 5, 2026 · Comments: "ICRA 2026 accepted"
          </p>

          <div className="research-highlight-strip">
            <div className="research-highlight-card">
              <span>Best task gain</span>
              <strong>+32 points</strong>
              <p>Pencil lead insertion improved from 26% to 58% reported success.</p>
            </div>
            <div className="research-highlight-card">
              <span>Self-touch modeling</span>
              <strong>r = 0.96 / 0.98</strong>
              <p>Reported tactile prediction correlations for thumb and index fingers.</p>
            </div>
            <div className="research-highlight-card">
              <span>Accepted venue</span>
              <strong>ICRA 2026</strong>
              <p>Conference acceptance is noted on the arXiv record.</p>
            </div>
          </div>
        </header>

        <div className="research-layout">
          <div className="research-main">
            <ResearchCard
              title="Abstract"
              subtitle="Problem framing and the core idea behind tactile sensory attenuation."
            >
              <p>
                Humans perform complex in-hand manipulation while multiple fingers
                simultaneously contact both the object and each other. A key enabling mechanism
                is sensory attenuation: predictable self-generated tactile sensations are
                down-weighted so unexpected, task-relevant stimuli stand out. TaSA transfers this
                principle to robotics with a two-stage learning pipeline: first learning
                self-touch dynamics from the robot&apos;s own actions, then integrating that predictor
                into downstream policy learning to emphasize object-contact signals for safer,
                more reliable manipulation.
              </p>
            </ResearchCard>

            <ResearchCard
              title="Method"
              subtitle="Two-phased predictive learning from self-touch modeling to attenuation-guided control."
            >
              <ol className="research-phase-list">
                {phases.map((phase) => (
                  <li key={phase.title} className="research-phase-item">
                    <h3>{phase.title}</h3>
                    <p>{phase.description}</p>
                  </li>
                ))}
              </ol>

              <div className="research-schematic">
                <div className="research-schematic-header">
                  <h3>TaSA pipeline</h3>
                  <p>
                    A method schematic based on the paper&apos;s reported training flow and attenuation
                    principle, replacing the empty figure slot with a concrete summary.
                  </p>
                </div>

                <div className="research-schematic-grid">
                  {pipelineStages.map((stage) => (
                    <div key={stage.title} className="research-schematic-card">
                      <span>{stage.label}</span>
                      <h4>{stage.title}</h4>
                      <p>{stage.description}</p>
                    </div>
                  ))}
                </div>

                <div className="research-schematic-footer">
                  <div className="research-signal research-signal-raw">
                    <span>Input</span>
                    <strong>Raw tactile and action history</strong>
                  </div>
                  <div className="research-signal research-signal-clean">
                    <span>Output</span>
                    <strong>Attenuated tactile representation for control</strong>
                  </div>
                </div>
              </div>
            </ResearchCard>

            <ResearchCard
              title="Experiments"
              subtitle="Insertion tasks requiring fine tactile discrimination under self-contact."
            >
              <div className="research-experiment-grid">
                {experiments.map((experiment) => (
                  <div key={experiment.title} className="research-experiment-card">
                    <h3>{experiment.title}</h3>
                    <p>{experiment.description}</p>
                  </div>
                ))}
              </div>

              <div className="research-results-table" role="table" aria-label="TaSA results">
                <div className="research-results-header" role="row">
                  <span>Task</span>
                  <span>RT only</span>
                  <span>TaSA</span>
                  <span>Gain</span>
                </div>

                {results.map((result) => (
                  <div key={result.task} className="research-results-row" role="row">
                    <div className="research-results-task">
                      <strong>{result.task}</strong>
                      <p>{result.detail}</p>
                    </div>
                    <span>{result.baseline}%</span>
                    <span>{result.tasa}%</span>
                    <span className="research-results-delta">{result.delta}</span>
                    <div className="research-results-bar">
                      <div className="research-results-track">
                        <div
                          className="research-results-baseline"
                          style={{ width: `${result.baseline}%` }}
                        />
                        <div
                          className="research-results-tasa"
                          style={{ width: `${result.tasa}%` }}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <ul className="research-results-notes">
                {resultNotes.map((note) => (
                  <li key={note}>{note}</li>
                ))}
              </ul>

              <p className="research-footnote">
                Results values are taken from the published evaluation summary for arXiv:2602.05468.
              </p>
            </ResearchCard>

            <ResearchCard
              title="Media"
              subtitle="Paper access points and public references currently available."
            >
              <div className="research-video-panel">
                <div className="research-video-copy">
                  <span>Demo video</span>
                  <h3>TaSA short demo</h3>
                  <p>
                    Local demo footage bundled with the site from <code>public/tasa short.mov</code>.
                  </p>
                </div>
                <div className="research-video-frame">
                  <video controls playsInline preload="metadata">
                    <source src={mediaVideoSrc} type="video/quicktime" />
                    Your browser does not support the embedded video player.
                  </video>
                </div>
              </div>

              <div className="research-media-grid">
                {mediaItems.map((item) => (
                  <a
                    key={item.href}
                    className="research-media-card"
                    href={item.href}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>{item.label}</span>
                    <h3>{item.title}</h3>
                    <p>{item.description}</p>
                  </a>
                ))}
              </div>

              <p className="research-footnote">
                This repository does not contain local figure exports or a bundled demo video, so
                the section links to the public paper assets for now and can be upgraded to direct
                embeds once those files are added.
              </p>
            </ResearchCard>
          </div>

          <aside className="research-sidebar">
            <ResearchCard title="Key contributions">
              <ul className="research-list">
                {contributions.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </ResearchCard>

            <ResearchCard title="At a glance">
              <div className="research-stat-stack">
                <div className="research-stat-card">
                  <span>Tasks</span>
                  <strong>3</strong>
                  <p>Pencil lead, coin, and paper-clip insertion settings.</p>
                </div>
                <div className="research-stat-card">
                  <span>Core idea</span>
                  <strong>Two-phased learning</strong>
                  <p>Predict self-touch first, then attenuate it during manipulation learning.</p>
                </div>
                <div className="research-stat-card">
                  <span>Reported outcome</span>
                  <strong>Higher success across all tasks</strong>
                  <p>TaSA outperformed the RT-only baseline in each summarized experiment.</p>
                </div>
              </div>
            </ResearchCard>

            <ResearchCard title="Citation">
              <div className="research-citation">
                <pre>
                  <code>{bibtex}</code>
                </pre>
                <CopyButton text={bibtex} />
              </div>
            </ResearchCard>
          </aside>
        </div>
      </section>
    </div>
  );
}

export default Research;
